-- cozinhas
INSERT INTO TB_COZINHA (id, NOME) VALUES(1, 'TAILANDESA');
INSERT INTO TB_COZINHA (id, NOME) VALUES(2, 'INDIANA');

-- restaurantes
INSERT INTO TB_RESTAURANTE (NOME, TAXA_FRETE, COZINHA_ID) VALUES ('Thai Gourmet', 10, 1);
INSERT INTO TB_RESTAURANTE (NOME, TAXA_FRETE, COZINHA_ID) VALUES ('Thai Delivery', 9.50, 1);
INSERT INTO TB_RESTAURANTE (NOME, TAXA_FRETE, COZINHA_ID) VALUES ('Tuk Tuk Comida Indiana', 15, 2 );

-- forma de pagamento
INSERT INTO TB_FORMA_PAGAMENTO (DESCRICAO) VALUES ('DINHEIRO');
INSERT INTO TB_FORMA_PAGAMENTO (DESCRICAO) VALUES ('DÉBITO');
INSERT INTO TB_FORMA_PAGAMENTO (DESCRICAO) VALUES ('CRÉDITO');
